name: practice_app_firebasee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.8

flutter:
  uses-material-design: true
